### ISSUE TITLE
StringCmd.val is not pub

### ISSUE THREAD

**Issue by KevinDaSilvaS** [Coachonko/redis#1]
The output of some operations return StringCmd.val as response, but the val property is not pub making it impossible to be accessed from external modules

**Comment by KevinDaSilvaS** [comment]
field `coachonko.redis.StringCmd.val` is not public

**Comment by KevinDaSilvaS** [comment]
discovered what I was doing wrong I forgot to treat val as function and not as a prop, thank you for your work!

**Comment by einar-hjortdal** [comment]
Can you please share a snippet of what you were doing wrong? Maybe I can improve the documentation

**Comment by KevinDaSilvaS** [comment]
Hi buddy, I discovered the problem it was me hehe
I was refering to  ```StringCmd.val``` as property instead of calling ```StringCmd.val()``` as function, but once I noticed what I was doing wrong, I just fixed my code, thank you!
